// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_3sz8HY7IvsPuRzMUOKvyhKzEnKH-Bc',
    appId: '1:141911106672:web:e22d5389caa66832cec0b5',
    messagingSenderId: '141911106672',
    projectId: 'mini-dating-app-protype-fd5ef',
    authDomain: 'mini-dating-app-protype-fd5ef.firebaseapp.com',
    storageBucket: 'mini-dating-app-protype-fd5ef.firebasestorage.app',
    measurementId: 'G-L41E1E8KGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF9RqHyN93nHb2u39p1Bl0_XYWavnQEd8',
    appId: '1:141911106672:android:37cfa012bb229670cec0b5',
    messagingSenderId: '141911106672',
    projectId: 'mini-dating-app-protype-fd5ef',
    storageBucket: 'mini-dating-app-protype-fd5ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD21NtAw1s-dmmZbkp6glSF1PNtbOaXYJU',
    appId: '1:141911106672:ios:c431d275c15f1ee1cec0b5',
    messagingSenderId: '141911106672',
    projectId: 'mini-dating-app-protype-fd5ef',
    storageBucket: 'mini-dating-app-protype-fd5ef.firebasestorage.app',
    iosBundleId: 'com.styematic.datingAppPrototype',
  );
}
